[package]
name = "diesel_demo"
version = "0.0.1"
authors = ["Vignesh Sankaran <developer@sankaran.io>"]

[dependencies]
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"